// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "fb8a11e0-d28a-4863-ac99-683241cdb4f8";

const char SSID[]     = "RC Mota";
const char PASS[]     = "RfmcxfQ6pzsw";
//const char SSID[]     = SECRET_SSID;    // Network SSID (name)
//const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

float humidity;
float pressure;
float temperature;
int light;
String weather_report;

void initProperties(){

  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(humidity, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(pressure, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperature, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(light, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(weather_report, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
